#
# barebox image generation Makefile for Allwinner sunxi eGON boot images
#

# %.egonimg - convert into eGON.BT0 image
# ----------------------------------------------------------------------
quiet_cmd_egon_image = EGON  $@
      cmd_egon_image = $(objtree)/scripts/egon_mkimage $< $@

$(obj)/%.egonimg: $(obj)/% FORCE
       $(call if_changed,egon_image)

# ----------------------------------------------------------------------
